language: python
sudo: false
python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r doc/developing/requirements.txt
  - pip install codecov

script:
  - coverage run main.py runtests
  - flake8 .

after_success:
  - codecov
