runtime: python37
threadsafe: true
instance_class: F4

handlers:
- url: /css
  static_dir: static/css
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /partials
  static_dir: static/partials
  secure: always

- url: /fonts
  static_dir: static/fonts
  secure: always

- url: /third_party
  static_dir: static/third_party
  secure: always

- url: /createdb
  script: scoreboard.wsgi.app
  secure: always
  login: admin

- url: /.*
  script: scoreboard.wsgi.app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.git/.*$
- ^.*.md$
- ^(.*/)?LICENSE$
- scoreboard/tests
